version: '2'
services:
  jenkins-master:
    build: 
      context: ./jenkins-master
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./jenkins-master/home:/var/jenkins_home"
  tomcat-qa:
    image: tomcat:8.0
    ports:
      - "8090:8080"
  tomcat-prod:
    image: tomcat:8.0
    ports:
      - "8091:8080"
  nexus:
    image: sonatype/nexus
    ports:
      - "5000:8081"